import json
import psycopg2
import os
from confluent_kafka import Consumer, KafkaError
from datetime import datetime
from dotenv import load_dotenv

load_dotenv()

DB_CONFIG = {
    "host":     os.getenv("DB_HOST"),
    "database": os.getenv("DB_NAME"),
    "user":     os.getenv("DB_USER"),
    "password": os.getenv("DB_PASSWORD")
}

TOPICS = [
    "supply_chain.public.inventory",
    "supply_chain.public.transport",
    "supply_chain.public.shipments",
    "supply_chain.public.sales",
    "supply_chain.public.forecasts",
]

# Track transaction IDs we generated to avoid feedback loop
processed_txids = set()

def get_connection():
    return psycopg2.connect(**DB_CONFIG)

def recalculate_inventory(row, conn, cur):
    sku_id  = row["sku_id"]
    zone_id = row["zone_id"]
    stock   = row["current_stock"]
    demand  = row["avg_daily_demand"]
    rop     = row["reorder_point"]
    lead    = row["lead_time_days"]

    days_of_stock = round(stock / demand, 1) if demand > 0 else 0
    reorder_qty   = max(0, int(rop * 1.5) - stock)
    days_overdue  = round(lead - days_of_stock, 1)

    if stock < rop * 0.5:
        status = "CRITICAL"
        action = f"Order immediately - {max(0, days_overdue)} days overdue"
    elif stock < rop:
        status = "WARNING"
        action = "Reorder soon"
    else:
        status = "HEALTHY"
        action = "Stock level OK"

    cur.execute("""
        UPDATE inventory SET
            days_of_stock   = %s,
            reorder_qty     = %s,
            status          = %s,
            action_required = %s,
            last_updated    = %s
        WHERE sku_id = %s AND zone_id = %s
    """, (days_of_stock, reorder_qty, status, action,
          datetime.now(), sku_id, zone_id))

    # Get the transaction ID we just created
    cur.execute("SELECT txid_current()")
    our_txid = cur.fetchone()[0]
    processed_txids.add(our_txid)

    conn.commit()
    print(f"Inventory updated — {sku_id} Zone {zone_id}: "
          f"stock={stock} status={status} days_left={days_of_stock}")

def recalculate_transport(row, conn, cur):
    lane_id    = row["lane_id"]
    on_time    = row["on_time"]
    damage     = row["damage_rate_pct"]
    delay_days = row["delay_days"]

    performance_score = round(
        (on_time * 40) +
        max(0, 30 - damage * 6) +
        max(0, 30 - delay_days * 10), 1
    )

    cur.execute("""
        UPDATE transport SET
            performance_score = %s,
            last_updated      = %s
        WHERE lane_id = %s
    """, (performance_score, datetime.now(), lane_id))

    cur.execute("SELECT txid_current()")
    processed_txids.add(cur.fetchone()[0])

    conn.commit()
    print(f"Transport updated — Lane {lane_id}: "
          f"score={performance_score}")

def recalculate_shipments(row, conn, cur):
    shipment_id = row["shipment_id"]
    status      = row["status"]
    delay_days  = row.get("delay_days", 0) or 0

    cur.execute("""
        UPDATE shipments SET
            delay_days   = %s,
            last_updated = %s
        WHERE shipment_id = %s
    """, (delay_days, datetime.now(), shipment_id))

    cur.execute("SELECT txid_current()")
    processed_txids.add(cur.fetchone()[0])

    conn.commit()
    print(f"Shipment updated — {shipment_id}: status={status}")

def recalculate_sales(row, conn, cur):
    print(f"Sale recorded — {row['sale_id']}: {row['sku_id']} "
          f"Zone {row['zone_id']} qty={row['quantity_sold']}")

def recalculate_forecasts(row, conn, cur):
    print(f"Forecast updated — {row['forecast_id']}: {row['sku_id']} "
          f"Zone {row['zone_id']} demand={row['forecasted_demand']}")

def process_event(topic, payload):
    op     = payload.get("op")
    after  = payload.get("after")
    source = payload.get("source", {})

    if op not in ["c", "u"] or not after:
        return

    # Check if this event was generated by our own consumer
    event_txid = source.get("txId")
    if event_txid and event_txid in processed_txids:
        print(f"Skipping our own update (txId={event_txid})")
        return

    conn = get_connection()
    cur  = conn.cursor()

    try:
        if "inventory" in topic:
            recalculate_inventory(after, conn, cur)
        elif "transport" in topic:
            recalculate_transport(after, conn, cur)
        elif "shipments" in topic:
            recalculate_shipments(after, conn, cur)
        elif "sales" in topic:
            recalculate_sales(after, conn, cur)
        elif "forecasts" in topic:
            recalculate_forecasts(after, conn, cur)
    except Exception as e:
        print(f"Error processing event: {e}")
        conn.rollback()
    finally:
        cur.close()
        conn.close()

def run():
    print("Kafka consumer starting...")
    print(f"Listening to {len(TOPICS)} topics\n")

    consumer = Consumer({
        "bootstrap.servers": "localhost:9092",
        "group.id":          "supply-chain-agent",
        "auto.offset.reset": "latest"
    })

    consumer.subscribe(TOPICS)

    try:
        while True:
            msg = consumer.poll(timeout=1.0)

            if msg is None:
                continue
            if msg.error():
                if msg.error().code() == KafkaError._PARTITION_EOF:
                    continue
                print(f"Kafka error: {msg.error()}")
                continue

            payload = json.loads(msg.value().decode("utf-8")).get("payload", {})
            op      = payload.get("op")
            topic   = msg.topic()

            if op == "r":
                continue

            print(f"Change detected on {topic} — op: {op}")
            process_event(topic, payload)

    except KeyboardInterrupt:
        print("Consumer stopped")
    finally:
        consumer.close()

if __name__ == "__main__":
    run()